### ISSUE TITLE
Installation from packages.amusewiki.org failed

### ISSUE THREAD

**Issue by tinglado** [melmothx/amusewiki#42] opened 2016-02-23 19:32 UTC
In a clean VM with debian jessie the installation fails when nginx is set up. Relevant part of the log:

    Setting up nginx-full (1.6.2-5+deb8u1) ...
    Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.
    invoke-rc.d: initscript nginx, action "start" failed.
    dpkg: error processing package nginx-full (--configure):
     subprocess installed post-installation script returned error exit status 1
    dpkg: dependency problems prevent configuration of nginx:
     nginx depends on nginx-full (>= 1.6.2-5+deb8u1) | nginx-light (>= 1.6.2-5+deb8u1) | nginx-extras (>= 1.6.2-5+deb8u1); however:
      Package nginx-full is not configured yet.
      Package nginx-light is not installed.
      Package nginx-extras is not installed.
     nginx depends on nginx-full (<< 1.6.2-5+deb8u1.1~) | nginx-light (<< 1.6.2-5+deb8u1.1~) | nginx-extras (<< 1.6.2-5+deb8u1.1~); however:
      Package nginx-full is not configured yet.
      Package nginx-light is not installed.
      Package nginx-extras is not installed.
    
    dpkg: error processing package nginx (--configure):
     dependency problems - leaving unconfigured
    dpkg: dependency problems prevent configuration of amusewiki:
     amusewiki depends on nginx; however:
      Package nginx is not configured yet.
      Package nginx-full which provides nginx is not configured yet.

    dpkg: error processing package amusewiki (--configure):
     dependency problems - leaving unconfigured

Finally, the log says:

    Errors were encountered while processing:
     nginx-full
     nginx
     amusewiki
    E: Sub-process /usr/bin/dpkg returned an error code (1)

I will provide the full log if it is necessary.

**Comment by melmothx** [comment] 2016-02-23 19:58
tinglado <notifications@github.com> writes:

> In a clean VM with debian jessie the installation fails when nginx is
> set up. Relevant part of the log:
>
> Setting up nginx-full (1.6.2-5+deb8u1) ...
> Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.
> invoke-rc.d: initscript nginx, action "start" failed.
> dpkg: error processing package nginx-full (--configure):
>  subprocess installed post-installation script returned error exit status 1
> dpkg: dependency problems prevent configuration of nginx:
>  nginx depends on nginx-full (>= 1.6.2-5+deb8u1) | nginx-light (>= 1.6.2-5+deb8u1) | nginx-extras (>= 1.6.2-5+deb8u1); however:
>   Package nginx-full is not configured yet.
>   Package nginx-light is not installed.
>   Package nginx-extras is not installed.

Thanks a lot for the report. I believe that this because amusewiki sets
the dependency on "nginx" which apparently has its own issues, being a
virtual package. I will dig if this is a debian bug for nginx (as I
think) or it's my fault (also possible) and provide a workaround ASAP.

I also believe that you can get past this point by installing nginx
prior to amusewiki and starting it up with "service nginx start".

If apt-get is stuck, probably you can run `dpkg -r nginx amusewiki` to
remove the offending packages, the `apt-get install nginx-full` and
`apt-get install amusewiki`.

-- 
Marco

**Comment by melmothx** [comment] 2016-02-24 18:14
Probably this issue was caused by nginx being unable to bind to port 80.

I've updated the package adding two missing prerequisites and I've updated the doc on http://packages.amusewiki.org

Closing for now, please reopen if the problem persist.

**Closed by melmothx** 2016-02-24 18:14 UTC
