### ISSUE TITLE
Search is case-sensitive

### ISSUE THREAD

**Issue by link2xt** [melmothx/amusewiki#247] opened 2018-11-26 11:49 UTC
For example, searching for `http://localhost:8080/search?query=rationale` gives 0 results, while searching for `http://localhost:8080/search?query=Rationale` gives 3 results. Also it seems that only the case of the first letter matters, as search for `http://localhost:8080/search?query=RAtIOnALE` gives 3 results as well.

Search found a similar issue with no solution: https://github.com/eprints/eprints/issues/165

**Comment by melmothx** [comment] 2018-11-26 15:09
@link2xt interesting enough, on the live site it seems fine. However, there are a couple of catches here. Texts are indexed stemmed using the text's language itself. However, for searching, the stemming is used only if there is a match between the the site's locale and the user's locale. Also the stemming on searching is disabled on multilanguage instances. That said, there are a couple of tests for these things. `t/xapian-multilang.t`. Not sure it's helping.

**Comment by melmothx** [comment] 2018-12-22 16:33
@link2xt could you please cherry-pick 7bf97b9b, run the `t/xapian.t` tests, and posts the output of 
`xapian-delve -a xapian/0xapian0`

I get

```
All terms in database: H0xapian0.amusewiki.org Kprova Len Qtest Sfr Slang Sxxxx XK/category/topic/prova XL1-5 XP2018 XQarticle ZKprova ZSfr ZSlang ZSxxxx Zbla Zetat Zfr Zlang Zxxxx Zétat bla etat fr lang xxxx état

```

**Comment by melmothx** [comment] 2018-12-22 16:35
@link2xt updated commit to cherry-pick, sorry.

**Comment by link2xt** [comment] 2018-12-22 21:57
The original bug report is about `http://localhost:8080/search?query=rationale` not returning any results. I can't reproduce it anymore.

**Comment by link2xt** [comment] 2018-12-22 22:41
As for xapian tests, changing the order of tests makes all of them pass.

**Comment by link2xt** [comment] 2018-12-22 22:50
Changing the order makes tests pass every time. Did lots of tests, it never fails.

Checking out master and removing the Russian test starting from `my $russian =<<MUSE;` and to the end of file still sometimes results in failure on French test.

After the test failure, I get this:
```
vagrant@amusewiki:/vagrant$ xapian-delve -a xapian/0xapian0
All terms in database: H0xapian0.amusewiki.org Kprova Len Qtest Sfr Slang Sxxxx XK/category/topic/prova XL1-5 XP2018 XQarticle ZKprova ZSfr ZSlang ZSxxxx Zbla Zfr Zlang Zxxxx bla fr lang xxxx
```

When they pass, I get this:
```
vagrant@amusewiki:/vagrant$ xapian-delve -a xapian/0xapian0
All terms in database: H0xapian0.amusewiki.org Kprova Len Qtest Sfr Slang Sxxxx XK/category/topic/prova XL1-5 XP2018 XQarticle ZKprova ZSfr ZSlang ZSxxxx Zbla Zetat Zfr Zlang Zxxxx Zétat bla etat fr lang xxxx état
```

**Comment by melmothx** [comment] 2018-12-22 23:37
Actually, I have an hypothesis. It looks like the only word with a character beyond ascii is missing the indexing on failure. IIRC, Search::Xapian module doesn't have a deep understanding of how encoding/decoding works in perl, so when indexing non-ascii character, it's a bit unclear what's happening. If I (or you) find a way to reproduce this consistently, I'd like to try what happens encoding the character on the `index_text` calls. 

https://github.com/xapian/xapian-docsprint/blob/master/language_specific/perl/index.rst

**Comment by link2xt** [comment] 2018-12-22 23:46
@melmothx 
> It looks like the only word with a character beyond ascii is missing the indexing on failure.

No, the problem is not with encoding. I have changed the test to use "foobar" instead.

```
diff --git a/t/xapian.t b/t/xapian.t
index c373f0f0..77e39527 100644
--- a/t/xapian.t
+++ b/t/xapian.t
@@ -77,9 +77,10 @@ for my $term ('XXXX', 'bla') {
 eval { $site->xapian->xapian_db->delete_document_by_term("Qtest") };
 ok !$@, "No exception deleting an already deleted doc";

-write_file($target, "#title XXXX#lang fr\n#SORTtopics prova\n\nBla bla État\n");
+write_file($target, "#title XXXX#lang fr\n#SORTtopics prova\n\nBla bla foobar\n");
 $site->update_db_from_tree;
-foreach my $term ("état", "etat", "ÉTAT", "ETAT") {
+$site->xapian_reindex_all;
+foreach my $term ("foobar", "Foobar", "fOOBAR", "FOOBAR") {
     my ($total, @results) = $site->xapian->search($term);
     is $total->total_entries, 1, "Found one record searching for $term";
 }
```

Now it fails with
```
#   Failed test 'Found one record searching for foobar'
#   at t/xapian.t line 85.
#          got: '0'
#     expected: '1'

#   Failed test 'Found one record searching for Foobar'
#   at t/xapian.t line 85.
#          got: '0'
#     expected: '1'

#   Failed test 'Found one record searching for fOOBAR'
#   at t/xapian.t line 85.
#          got: '0'
#     expected: '1'

#   Failed test 'Found one record searching for FOOBAR'
#   at t/xapian.t line 85.
#          got: '0'
#     expected: '1'
```

**Comment by link2xt** [comment] 2018-12-22 23:59
The problem is fixed for me with the following patch:
```
diff --git a/t/xapian.t b/t/xapian.t
index c373f0f0..b019e8b6 100644
--- a/t/xapian.t
+++ b/t/xapian.t
@@ -77,6 +77,8 @@ for my $term ('XXXX', 'bla') {
 eval { $site->xapian->xapian_db->delete_document_by_term("Qtest") };
 ok !$@, "No exception deleting an already deleted doc";

+sleep 1;
+
 write_file($target, "#title XXXX#lang fr\n#SORTtopics prova\n\nBla bla État\n");
 $site->update_db_from_tree;
 foreach my $term ("état", "etat", "ÉTAT", "ETAT") {
```

**Comment by melmothx** [comment] 2022-11-14 08:00
Closing this. Too old and problem was unclear in first place.

**Closed by melmothx** 2022-11-14 08:00 UTC
Labels: more-info-needed
