### ISSUE TITLE
One chapter per page?

### ISSUE THREAD

**Issue by seth1** [melmothx/amusewiki#208] opened 2018-08-20 03:19 UTC
It seems the present feature is to fit an entire book into one page and have a table of contents at the top that links to subsections of the page. I was wondering if it would be possible to have each chapter on it's own page as some books are quite long, perhaps sort of like making the 'subbooks' of a 'book' like subcategories are of categories.

If this has already been implemented, I apologize.

**Comment by melmothx** [comment] 2018-08-20 18:12
seth1 <notifications@github.com> writes:

> It seems the present feature is to fit an entire book into one page
> and have a table of contents at the top that links to subsections of
> the page. I was wondering if it would be possible to have each chapter
> on it's own page as some books are quite long, perhaps sort of like
> making the 'subbooks' of a 'book' like subcategories are of
> categories.

Hello there,

I understand the question, but I don't see the gain of splitting a book
by chapter. Basically everything on amusewiki is built assuming that 1
text (whatever its length) is stored in 1 file.

Also, with the bookbuild you can select the individual chapters for
reading.

So, I'd ask what's the context of this request, maybe I'm missing
something.

Cheers

--
Marco

**Comment by seth1** [comment] 2018-08-20 21:23
Yeah that makes sense.

The main reason for my request is trying to make searching through multihundred page books more user friendly. Currently if one searches for a sentence, it returns the book, but then it's left to the user to find it in the book (not too hard with ctrl+f, but could be more 'instant'). My thought was to split it by chapters so they find the section easier, but you're right that would break 'one text one file' philosophy.

I don't know if amusewiki was ever intended for such long books, but I see it being used that way. I'm just curious if there's anything that can be done to help people find the 'section' of the book they're looking for faster.

**Comment by melmothx** [comment] 2018-08-20 21:36
seth1 <notifications@github.com> writes:

> The main reason for my request is trying to make searching through
> multihundred page books more user friendly. Currently if one searches
> for a sentence, it returns the book, but then it's left to the user to
> find it in the book (not too hard with ctrl+f, but could be more
> 'instant'). My thought was to split it by chapters so they find the
> section easier, but you're right that would break 'one text one file'
> philosophy.

Well, if it's a search problem, I believe it should be solved on the
indexing/search side.

> I don't know if amusewiki was ever intended for such long books, but I
> see it being used that way. I'm just curious if there's anything that
> can be done to help people find the 'section' of the book they're
> looking for faster.

Yes, it was intended for long books as well. Expecially importing texts
from sites which used the split-chapter approach was particularly
painful, hence the 1 text == 1 file approach.

I can't promise a quick fix for this, but it's totally worth the effort.

**Comment by melmothx** [comment] 2020-01-06 19:16
Still missing the documentation but the implementation is in master.

**Closed** 2020-01-06 19:16 UTC
